### ISSUE TITLE
REST API: NameError("global name 'moduleName' is not defined",)

### ISSUE THREAD

**Issue by interference-security** [adaptivethreat/EmPyre#10]
The following modules return an error message `NameError("global name 'moduleName' is not defined",)` when executed using REST API call:

1. collection/osx/native_screenshot
2. collection/osx/screenshot
3. collection/osx/webcam

Request:
```
POST /api/modules/collection/osx/native_screenshot?token=dx6dc587i35yyf11yq3oohdq5wadcqeyaxg9ou7s HTTP/1.1
Host: 127.0.0.1:1337
Accept: */*
Content-Type: application/json
Content-Length: 43
Connection: close

{"Agent":"Mac","SavePath":"\/tmp\/out.png"}
```

Response:
```
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 53
Server: Werkzeug/0.10.4
Date: Sat, 14 May 2016 08:31:03 GMT

NameError("global name 'moduleName' is not defined",)
```

**Comment by HarmJ0y** [comment]
Thanks for the heads up, sorry this took so long to get to. We're checking into it now.

**Comment by HarmJ0y** [comment]
This should be fixed with https://github.com/adaptivethreat/EmPyre/commit/d45169b8ae3c66e53c7ccdb7a94108421d5153b0 . If that doesn't resolve, please reopen the issue.
