### ISSUE TITLE
Use ENV to identify Python

### ISSUE THREAD

**Issue by cutaway** [adaptivethreat/EmPyre#11]
While installing no OS X I was having issues with EmPyre recognizing my Python version. I updated "empyre" and "setup/setup_database.py" files so that Python is called using: `#!/usr/bin/env python`

Not sure if there are other files to modify (yet) or if this could cause other issues. But it might be helpful for others.

cutaway

**Comment by killswitch-GUI** [comment]
@cutaway hey thanks for bringing this up. Currently we have yet to setup server side on OS X, but we can look into running it on this platform of course. I also have no idea what issues you could have in the future.

**Comment by cutaway** [comment]
Ah, I see, no problem. This update should work the same for Linux-distros, so shouldn't have a negative impact. Since I already have it installed I'll see what happens and post any useful findings here. It I have a bunch of issue I'll just switch to a Linux-Bistro. 

Thank you for your work on this project. I think this is closed but I'll let you do it if you want to track that update.

cutaway

**Comment by rvrsh3ll** [comment]
cutaway,

I just got it working by running "sudo easy_install pip" then run "sudo ./install". Give that a shot first and let me know if it works.

**Comment by HarmJ0y** [comment]
As there's been no response for nearly a month, I'm going to close this one out. If it's still an issue, feel free to reopen.
