### ISSUE TITLE
socket.error when getting the internal IP address

### ISSUE THREAD

**Issue by imaibou** [adaptivethreat/EmPyre#22]
Hello,
The instruction x.connect(("10.0.0.0", 80)) (https://github.com/adaptivethreat/EmPyre/blob/master/data/agent/stager.py#L599) causes an error (socket.error: [Errno 51] Network is unreachable) when the target's IP address is not in the 10.0.0.0 network (in my case, it was 192.168.56.1). I don't know if it is very important to get the internal IP address at this stage since one can just do a (shell ifconfig) when interacting with the victim. Or may be there is a better way to get the IP address. At the very least, we could add a try/except for this instruction.

**Comment by rvrsh3ll** [comment]
Hello, thank you for the issue report. I currently tested a fix using "socket.gethostbyname(socket.gethostname())" and it seems to be working well. Try that if you can and we'll do some more testing on this end as well. Hope to close this soon.

**Comment by imaibou** [comment]
That's perfect, it works on my OSX El Capitan and gives the right internal IP address. thanks for the fix.

**Comment by rvrsh3ll** [comment]
Excellent! We're pushing a fix to the dev branch which will soon become the next version merge. Thanks for your help!
