### ISSUE TITLE
error executing specified Python data on office 2016

### ISSUE THREAD

**Issue by imaibou** [adaptivethreat/EmPyre#23]
Hello,
today we tried to execute the collection/osx/screenshot module on a OSX El Capitan using the macro stager. We did not know however that Excel 2016 on Mac executes macros in a sandbox environment, giving us almost no permissions. Not knowing that, we launched the previously mentioned module with the default value of SavePath (/tmp/out.png), and for the lack of privileges, the agent's payload crashed and we lost contact, in the logs of the agent, we found the following error:
"[!] Error response: error executing specified Python data [Errno 2] No such file or directory: '/tmp/out.png' 
Buffer data recovered:

".
We recommend using a try/except statement to avoid the crashing of the payload, and we hope you add a note of this behavior (sandbox on office 2016) in the description of the stager so that the future users know what to expect.

**Comment by HarmJ0y** [comment]
Thanks for the heads up on Office 2016, it's something we've heard from a few others but haven't been able to test yet.

Alex, are you able to check into this so the agent can at least exit gracefully?

**Comment by killswitch-GUI** [comment]
Tupi can dig into this.

**Comment by killswitch-GUI** [comment]
Yup*

**Comment by killswitch-GUI** [comment]
@imaibou This is deffiently a issue I need to look into, right now we do handle errors on failed modules both on the server and agent (https://github.com/adaptivethreat/EmPyre/blob/master/data/agent/agent.py#L349). Let me dig a bit deeper

**Comment by rvrsh3ll** [comment]
This has been fixed and pushed to Dev branch. The agent will now check for both little snitch and sandboxes. The agent will not call back if either are true. Thanks for the input!

**Comment by imaibou** [comment]
Why block the agent when the stager is sandboxed? there are still things you can do, like read the clipboard, get screenshots after finding a writable folder (which is the current location the stager is executed on) and maybe other things. I would have just made a test to see if the module has enough rights to write into a file before writing so that the agent wouldn't crash.

**Comment by imaibou** [comment]
I propose to separate the little snitch treatment from the sandbox treatment. This way, the user can interact with the stager even when sandboxed and in the same time avoid detection by little snitch by using the configuration "littleSnitch=true" and "sandbox=false".

**Comment by rvrsh3ll** [comment]
Have you tested the clipboard grab from the sandbox?

**Comment by imaibou** [comment]
yes it works, taking screenshots also works when changing the temporary folder to a writable folder. I propose you revert the last commit you made, and I will try to test all the different empyre modules to see which ones work on a sandboxed environment. We can add a tag to each module like the "OpsecSafe" for example, and we can call it SandboxSafe or something. Like I said on my last comment, I propose we fork the "safechecks" switch to two separate switches: "littlesnitch" and "sandbox", this way the user can make a choice. I may have some free time these days so I will test the different modules and make a pull request.

**Comment by rvrsh3ll** [comment]
What if the agent just printed out that it's operating in a sandbox? Is that what you're going for? Just knowing that the agent is in a sandbox?

**Comment by imaibou** [comment]
That would be a good start, and if sandbox mode is detected, we could change some default settings for some modules to make them work even in sandbox (if that is possible), as an example, we can change the "SavePath" parameter in the "collection/osx/screenshot" module to point to a file in the current directory instead of /tmp/out.png like shown in the screenshot. plus, it would be nice to know
 for each module if it works in sandbox mode.
![screenshot from 2016-08-13 00-30-56](https://cloud.githubusercontent.com/assets/3109250/17638910/f18c52a8-60ed-11e6-8312-605c1eabe5b0.png)

**Comment by rvrsh3ll** [comment]
Sweet! Sounds good.

**Comment by rvrsh3ll** [comment]
Revert complete!
