### ISSUE TITLE
Missing pip dependency in install chain

### ISSUE THREAD

**Issue by Winterspite** [adaptivethreat/EmPyre#28]
## EmPyre Version
Checkout of `master` on 2016-07-07

## OS Information (Linux flavor, Python version)
Ubuntu 14.04.4 LTS, Python 2.7.6 (default, Jun 22 2015, 17:58:13) 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When running ./setup/install.sh on a brand new AWS/Ubuntu install, it throws errors about pip not existing.

## Screenshot of error, embedded text output, or Pastebin link to the error
```
Preparing to unpack .../swig_2.0.11-1ubuntu2_amd64.deb ...
Unpacking swig (2.0.11-1ubuntu2) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up swig2.0 (2.0.11-1ubuntu2) ...
Setting up swig (2.0.11-1ubuntu2) ...
setup/install.sh: line 40: pip: command not found
setup/install.sh: line 41: pip: command not found
setup/install.sh: line 42: pip: command not found
setup/install.sh: line 43: pip: command not found
setup/install.sh: line 44: pip: command not found
Traceback (most recent call last):
  File "./setup_database.py", line 4, in <module>
    from Crypto.Random import random
ImportError: No module named Crypto.Random
```

## Any additional information
Solution should be as simple as adding `python-pip` to the install script as one of the earlier dependencies.

**Comment by killswitch-GUI** [comment]
Thanks for the heads up.We tested on AWS and it turns out pip isn't default, I appreciate you taking the time to bring it to our attention. It should be fixed, let me know if toy have any more issues.

**Comment by killswitch-GUI** [comment]
Fixed.
