### ISSUE TITLE
[suggestion]  Duckyscript stager?

### ISSUE THREAD

**Issue by thesle3p** [adaptivethreat/EmPyre#30]
I see there is a Teensy stager, are there any plans to add a USB Rubber Ducky  stager as well? It would make deploying  EmPyre via Kali Nethunter or USB Rubber Ducky easier.

**Comment by n00shE** [comment]
yes please

**Comment by xorrior** [comment]
I'll look into this

**Comment by xorrior** [comment]
Duckyscript stager has been added. Please test it out and let us know.
