### ISSUE TITLE
socket.gethostbyname(socket.gethostname()) got an error

### ISSUE THREAD

**Issue by cdrf** [adaptivethreat/EmPyre#31]
## EmPyre Version
1.0.1

## OS Information (Linux flavor, Python version)
OS X EI Capitan 10.11.5
Python 2.7.10

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
run default launcher got an python error:
`socket.gaierror: [Errno 8] nodename nor servname provided, or not known`
I found it occurs from here : 
` internalIP = internalIP = socket.gethostbyname(socket.gethostname())`
So I think the way you get internal IP is not compatible enough

## Any additional information
http://stackoverflow.com/questions/16332065/finding-ip-address-using-pythons-socket-module
http://stackoverflow.com/questions/31507434/how-to-solve-python-socket-error

**Comment by cdrf** [comment]
btw I found EmPyre is not designed to running on MAC OS ? Because the install.sh is not support MAC very well.

**Comment by rvrsh3ll** [comment]
Correct, the controller is currently supported on Linux OS's only. This "may" change in the future. Closing for now.
