### ISSUE TITLE
Feature request - Empire mariage

### ISSUE THREAD

**Issue by tristandostaler** [adaptivethreat/EmPyre#32]
First, nice job for this project, it looks really promising! 

Second, I think it would be not to difficult to add some code to the empire project to make it possible to use this project also? That way, you got 1 C&C for all platforms.

I think of something like adding in the DB if the agents is a python or a powershell agent and then calling different directories and python files.

Let's say i call:
agents -> interact RandomAgent -> usemodule [tab][tab] -> {if agent.isPython: showPythonModules()} -> etc.

**Comment by HarmJ0y** [comment]
You're definitely thinking along the same lines as us! The plan post BlackHat/DEF CON is to merge the code bases so there's a single platform.

**Comment by tristandostaler** [comment]
Ok, really nice!!
