### ISSUE TITLE
Need help porting script to module

### ISSUE THREAD

**Issue by n00py** [adaptivethreat/EmPyre#36]
I have a python script that I think would do well as an EmPyre persistence module:

https://github.com/n00py/MailPersist

I attempted to port it over myself, but after spending hours trying to make it work, I was not able to.  Is there anyone who can help me with this?

Part of the reason I am having trouble is the the "script" portion is ran, I can't see the stack trace when it has issues, which makes troubleshooting difficult. 

def generate(self):
 return script    <------- this 

Is there a way I can somehow capture this information?  I'm fairly new to Python.

**Comment by xorrior** [comment]
When starting EmPyre, you can use the '--debug' flag. This will output the last module ran as a python script in the EmPyre root directory. That should give you a good place to start.
