### ISSUE TITLE
Dylib Hijack not working 

### ISSUE THREAD

**Issue by n00py** [adaptivethreat/EmPyre#40]
## EmPyre Version
1.0.1

## OS Information (Linux flavor, Python version)
Darwin 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

Aka El Capitan 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
The Dylib Hijacker scanner and Creator do not work.  The scanner produces no output.  When I run --debug and copy the code onto the host, it works.  But not from the server.  

Same goes for the Hijacker.  Nothing in the console.  Ran on the host, it "seems" to work.  

## Screenshot of error, embedded text output, or Pastebin link to the error

![screen shot 2016-09-29 at 10 29 35 pm](https://cloud.githubusercontent.com/assets/14309124/18981547/45a8e84e-8694-11e6-88d8-bad16e70e410.png)

Scanner module ran Locally.  Seems to work.

Config of CreateHijacker:
```
 Name                Required    Value                    
  ----                --------    -------                 
  LittleSnitch        True        True                      
  VulnerableRPATH     True        /Applications/Xcode.app/Contents/Frameworks/DVTFoundation.framework/Versions/A/DVTFoundation    
  Agent               True        None                           
  Listener            True        newtest                         
  LegitimateDylibPath True        /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/DVTFoundation         
  UserAgent           False       default                                                                        
  Arch                True        x64       
```
![screen shot 2016-09-29 at 10 26 03 pm](https://cloud.githubusercontent.com/assets/14309124/18981506/bea55120-8693-11e6-816c-33f470bbf55f.png)

Sceenshot of the debug script run on the host.  Output shows that it was successful.  Evil Dylib shows up where it is supposed to be.  Running Xcode does not spawn listener.

**Comment by xorrior** [comment]
I tested this and it looks like the Dylib isn't being created properly. I'll have to review the logic for that and get back to you.

**Comment by xorrior** [comment]
@n00py Can you test this again in the dev branch? I just pushed some code that hopefully fixes the CreateHijacker module. 

In regards to the HijackScanner, how long did you wait to view the results? The scan takes roughly 3-4 mins with default settings, depending on the number of dylibs/macho's binaries present on the system. Can you try the scanner module again and wait 3-5 mins for output? Let me know.

**Comment by n00py** [comment]
Just tried, still no luck.
git clone -b dev https://github.com/adaptivethreat/EmPyre.git
Server is Debian 8
Host is El Capitan 

Spartan@Leo:/Applications/Xcode.app/Contents/Frameworks/DVTFoundation.framework/Versions/A$ ls -lah
total 24
drwxr-xr-x  3 root  wheel   102B Oct  3 20:03 ./
drwxr-xr-x  3 root  wheel   102B Sep 29 22:11 ../
-rwxrwxrwx  1 root  wheel   8.8K Oct  3 20:03 DVTFoundation*
Spartan@Leo:/Applications/Xcode.app/Contents/Frameworks/DVTFoundation.framework/Versions/A$ 

I get no output in the terminal for either script.
It's still creating the Dylib, at least.  Maybe it's just me.

**Comment by xorrior** [comment]
Ok, after some testing and review of the module code, the dylib's are being created properly. It looks like the issue may be with Xcode itself. I am currently using Xcode v8. I know that the hijack worked for the previous version. Can you try to use the CreateHijacker module for another vulnerability? I was able to successfully hijack the PhotoStreamAgent for iPhoto. Additionally, can you set the env variable for DYLD_PRINT_RPATHS with export DYLD_PRINT_RPATHS="1"? After completing, the module, be sure the open the application through terminal. The output should show whether the rpath leading to the hijacker successfully expanded or not. I will try to review the release notes for the new version and any recent patches to pinpoint if there has been any changes specific to dylib hijacking vulnerabilities. Keep in mind that dylib hijacks vary depending on the application and how library functions are called upon. So you may find that some hijacks don't work at all or only work when certain functionality is used. 

In regards to the HijackScanner I am not able to reproduce this issue. I receive output from the module after waiting roughly 4 minutes. I am going to test the module on OSX El Capitan at some point today.

**Comment by xorrior** [comment]
I'm going to go ahead and close this.
