### ISSUE TITLE
Support in Bash on Windows

### ISSUE THREAD

**Issue by mattifestation** [adaptivethreat/EmPyre#6]
I've been derping it up with PowerShell so I'd rather just run EmPyre in Bash on Windows instead of Empire. Why don't you support that yet?

**Comment by mattifestation** [comment]
Meh. I'll use pupy RAT. It's better than Empire anyway...

**Comment by HarmJ0y** [comment]
<img width="640" alt="disqualified" src="https://cloud.githubusercontent.com/assets/5504523/15231838/551e367c-1852-11e6-9251-742f4c04898e.png">
