### ISSUE TITLE
Errno 99 Cannot assign requested address

### ISSUE THREAD

**Issue by Renek42** [adaptivethreat/EmPyre#8]
When assigning an external IP for EmPyre to listen on it throws an error as seen below: 

![empyre_error](https://cloud.githubusercontent.com/assets/12804590/15262338/583dc478-1927-11e6-9423-4c6907750fec.jpg)

VM is an AWS instance with an assigned local IP of 172.blah and an external of 54.blah. When trying to tell EmPyre to listen on the external 54.blah IP, it throws the error. I also use Empire on this box and can assign an external IP with no issue.

**Comment by killswitch-GUI** [comment]
Can you please confirm your running in a privliaged state (root)? This is easy to look over since the default port is 8080 and we trust that the user will run with either sudo or as root for non Ephemeral ports.

**Comment by jtomkiel** [comment]
I can verify this as well on my AWS instance also.  Running as root.  When setting the Host to the external IP address, doesn't matter what port is specified, I get the error saying the port selected is in use already.  Setting the Host to the internal IP allows the listener to execute but of course at that point you can't connect from the outside.

![screenshot-error-as-root](https://cloud.githubusercontent.com/assets/10123760/15307673/5d6c3186-1ba3-11e6-8f62-bb0874705136.jpg)

**Comment by killswitch-GUI** [comment]
Can I please get the details on the AWS image? I just tested on the Ubuntu image on AWS no issue.

**Comment by HarmJ0y** [comment]
I'm going to close this out as there hasn't been a response in nearly a month. If the issue still remains with repeatable steps, please feel free to reopen.

**Comment by mattchess50** [comment]
I'm observing this same issue as shown in the screenshot jtomkiel posted.  If the 'Host' is set to something other than the local address the error occurs.

**Comment by Und3rf10w** [comment]
I am able to replicate this on a clean Ubuntu AWS image. Issue arises when the listener ```Host``` option is set to an IP address (such as the public IP of the server). If the ```Host``` option is set to a domain name, then it works.

FAIL: http://52.X.X.X
SUCCESS: c2.example.com
SUCCESS: http://172.31.X.X

**Comment by Njoiyt** [comment]
Underflow is right. Something might have changed with empire, but on an older version I was able to set the host ip to my redirector and still start the listener. It would seem now that empire requires that this interface be on your host. 
For example:

redirector: 1.1.1.1
empire-lp: 192.168.1.100

I too was able to get around this by using a fqdn.

![error](https://cloud.githubusercontent.com/assets/23488474/20329043/026d83ba-ab64-11e6-9943-db546cc36f38.png)
